language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install cppcheck

os:
  - linux

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make TEST
  - valgrind ./TEST
  - ls
  - cd ..
  - cppcheck —inconclusive —enable=all —check-config —suppress=missingIncludeSystem -I include —language=c libs

after_script:
  - make clean
